# Generated by Django 4.1 on 2022-08-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='cellphone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
